pool:
  name: LocalPoolEmin

resources:
  repositories:
  - repository: main
    type: github
    name: eminturan/azure-git-pull-push
    trigger:
      branches:
        include:
        - main
    endpoint: eminturan


  - repository: helm
    type: github
    name: eminturan/azure-helm-repo
    ref: refs/heads/main
    endpoint: eminturan


stages:
- stage: Deneme
  displayName: Deneme
  jobs:
  - job: DenemeJob
    displayName: DenemeJob
    steps:
    - checkout: helm
    - task: CmdLine@2
      displayName: denemetask
      inputs:
        script: |
          ls -l
          pwd
