pool:
  name: LocalPoolEmin

resources:
  repositories:
  - repository: main
    type: github
    name: eminturan/azure-git-pull-push
    trigger:
      branches:
        include:
        - main
    endpoint: eminturan


  - repository: helm
    type: github
    name: eminturan/azure-helm-repo
    ref: refs/heads/main
    endpoint: eminturan


stages:
- stage: Deneme
  displayName: Deneme
  jobs:
  - job: DenemeJob
    displayName: DenemeJob
    steps:
    - checkout: main
    - checkout: helm
      persistCredentials: true
    - task: CmdLine@2
      displayName: denemetask
      inputs:
        script: |
          ls -l
          pwd

          echo 'Change Value'
          echo '------------'
          cd azure-helm-repo/deneme-chart/
          sed 's/^\(  tag: \).*$/\11.2.3/' values.yaml > temp.yaml
          mv temp.yaml values.yaml

          cat values.yaml


          echo 'Git Push'
          echo '------------'
          git branch
          git add .
          git commit -am "values.yaml updated"
          git push origin HEAD:main
